### ISSUE TITLE
Fairybread throws with the latest (11.1.0-preview.50)

### ISSUE THREAD

**Issue by eugenpaval** [benmccallum/fairybread#37]
On the very first query (not a mutation where the validator is supposed to be invoked) I get errors back:
 "errors": [
    {
      "message": "Method not found: 'System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.Object> HotChocolate.Types.IField.get_ContextData()'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "schema"
      ],
      "extensions": {
        "errorChain": [],
        "stackTrace": [
          "   at FairyBread.DefaultFairyBreadOptions.DefaultImplementations.ShouldValidateBasedOnValidateDescriptor(IMiddlewareContext context, IInputField argument)",
          "   at FairyBread.DefaultFairyBreadOptions.DefaultImplementations.ShouldValidate(IMiddlewareContext context, IInputField argument)",
          "   at FairyBread.InputValidationMiddleware.InvokeAsync(IMiddlewareContext context)",
          "   at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)",
          "   at HotChocolate.Execution.Processing.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)",
          "   at HotChocolate.Execution.Processing.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
        ]
      }
    }
  ] (edited)

**Comment by benmccallum** [comment]
Hey @eugenpaval , I can't reproduce this. Potentially you're on an old FairyBread version so upgrade to 4 and that should solve it. I maintain a compatibility table here as best I can: https://github.com/benmccallum/fairybread#compatibility

Let me know how you go!

**Comment by eugenpaval** [comment]
No, still get the error. These are all my nuget packages

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.0.78" />
    <PackageReference Include="FairyBread" Version="4.1.0" />
    <PackageReference Include="FluentValidation" Version="9.5.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="9.5.1" />
    <PackageReference Include="Flurl.Http" Version="3.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="5.0.0" />
    <PackageReference Include="MySqlConnector" Version="1.2.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.4.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.Async" Version="1.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.0.5" />
    <PackageReference Include="Serilog" Version="2.10.1-dev-01256" />
    <PackageReference Include="Serilog.Sinks.Console" Version="4.0.0-dev-00839" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0-dev-00905" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="11.1.0-preview.50" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="11.1.0-preview.50" />
    <PackageReference Include="HotChocolate.AspNetCore.Voyager" Version="10.5.5" />
    <PackageReference Include="HotChocolate.Types.Filters" Version="11.1.0-preview.50" />
    <PackageReference Include="HotChocolate.Types.Sorting" Version="11.1.0-preview.50" />
    <PackageReference Include="Microsoft.Identity.Web" Version="1.6.0" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="1.6.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
    <PackageReference Include="System.Linq.Async" Version="5.0.0" />
    <PackageReference Include="System.Reactive" Version="5.0.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.8.1" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.8.1" />
    <PackageReference Include="Websocket.Client" Version="4.3.30" />
  </ItemGroup>

Server starts ok but on first query (not even a mutation where I employ FairyBread validation) I get the error
Method not found: 'System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.Object> HotChocolate.Types.IField.get_ContextData()'.

My GQL Schema  implementation is pure code first. 
FairyBread is added with
               services .AddFairyBread(options => options.AssembliesToScanForValidators = new [] { Assembly.GetExecutingAssembly() } );

I have one validator
    public class ExplicitSchemaProviderValidator : AbstractValidator<ExplicitSchemaProvider>
    {
	…
    }
But it doesn’t get called since this is for a mutation and I am making a query.

Removing AddFairyBread call makes everything work again.

**Comment by JardarM** [comment]
Hi, could be that it is related to .net 5 somehow. I downloaded the project and set the framework to 3.1, for both my application and the fairybread project and got it to work.

**Comment by benmccallum** [comment]
@eugenpaval , it doesn't seem like pasted your nuget package versions :P 

@JardarM , could you post yours also. I think you might be right, perhaps HC are doing some target framework code toggling, but it's still bizarre because I'm multi-targeting too and have a test suite that runs on `netstandard2.0`, `netcoreapp3.1` and `net5.0`...

FYI @eugenpaval, in 4.1 you won't need to set `AssembliesToScanForValidators` ;)

**Comment by JardarM** [comment]
Project structure with packet references
Application - TargetFramework = net5.0
* FairyBread: 4.1.0
* FluentValidation.AspNetCore 9.5.1
* HotChocolate.AspNetCore 11.0.9
* GQLModel
GQLModel - TargetFramework = netcoreapp3.1
* FairyBread: 4.1.0
* HotChocolate.Types 11.0.9

**Comment by benmccallum** [comment]
@PascalSenn and @michaelstaib, 

I've been trying to chase down this missing method exception:
`'System.Collections.Generic.IReadOnlyDictionary`2<System.String,System.Object> HotChocolate.Types.IField.get_ContextData()'`

Likely caused by this change in HC:
https://github.com/ChilliCream/hotchocolate/commit/712d3bdfba0708c134afa4c551748a05166e59f3#diff-c3e08a25cf6700759e0a640e3efee6e49035233bd72bea268b156890ac15c082

@JardarM has kindly shown me their dependency setup. Interestingly he is using `net5.0` for the web app and `netcoreapp3.1` for another project that the app depends on for his models/graph types. In my mind this sounds like a dangerous combination to be running. Is this something I should try and figure out how to support? 

I think @eugenpaval 's situation could be different but until he shares his dependency tree I can't help him much further there.

**Comment by benmccallum** [comment]
Ahhh, I think because I'm targeting a minimum if v11.0.0, so FairyBread is compiled against a version that expects to find `ContextData` on `IField` but now it's on `IHasReadOnlyContextData`...

**Comment by benmccallum** [comment]
It's was weird how I was unable to produce it, but I guess because when I target 11.0.9 in my local project, it's recomipling FairyBread against the new location of that property and all is fine. But if I took FairyBread's nuget package and try to do this it'll blow up as it's already compiled and that method is in fact now missing.

I guess I'll release a 4.1.1 that fixes this and is recompiled/re-targeted against 11.0.9.

**Comment by benmccallum** [comment]
Yep, confirmed that if I targeted 11.0.9 and ran tests without re-building, I got this exception and the tests failed. Doing a rebuild then running the tests, they passed.

**Comment by benmccallum** [comment]
@JardarM and @eugenpaval , this should be fixed in v4.1.1 which will be released in a few minutes. Will close but do let me know if you've still got issues on v4.1.1. Thanks for reporting and sorry it was a tricky one to figure out as the unit tests were fine but only because they were re-compiling FairyBread each time to be compatible :P TIL!

**Comment by eugenpaval** [comment]
Thanks a lot Ben, I was out for about 8 days and was totally disconnected from outside world :) on purpose... will try it out and let you know - great addition to HC btw!
